### ISSUE TITLE
Missing esm2_t33_650M_UR50D.pt

### ISSUE THREAD

**Issue by michoug** [nlm-irp-jianglab/SpikeHunter#1]
Hi
While running the test proteins, I got this error

FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/gsfs12/users/Irp-jiang/share/yyang/ESM/checkpoints/esm2_t33_650M_UR50D.pt'

Where can I find this file?
Cheers
Greg

**Comment by YiyanYang0728** [comment]
Hi Greg,

Thanks for your interest in SpikeHunter. We updated the installation by adding a step 4:
```
# get esm2 model
wget https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50D.pt

# please go to https://figshare.com/articles/online_resource/SpikeHunter_trained_model_pth_file/23577051 to download model_best.pth and copy it to trained_model/ folder
```
Hope this will help you to run it without issues.

Best,
Yiyan
